# Generated by Django 4.2.5 on 2023-10-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='first_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to=settings.AUTH_USER_MODEL, verbose_name='ilk kullanıcı'),
        ),
        migrations.AddField(
            model_name='room',
            name='secon_duser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconduser', to=settings.AUTH_USER_MODEL, verbose_name='ikinci kullanıcı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
