# Generated by Django 4.2.5 on 2023-10-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_first_user_room_secon_duser_alter_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='secon_duser',
            new_name='second_user',
        ),
    ]
